### PR TITLE
Adding more error types

### PR DESCRIPTION
**Pull request by franciscofsales**
### Summary

Small changes to add more error types (responding to issue #48 )

### Other Information

Tests and docs updates included.

### CODE REVIEW

**Comment by daffl** [comment]
Awesome! Only comment is that you don't need to update the version or changelog, it'll do that automatically when we make the release.

**Comment by franciscofsales** [comment]
Sorry, was not aware of that. Will take into account next time. Thanks

**Comment by slajax** [comment]
LGTM! Thanks @franciscofsales

**Comment by daffl** [comment]
Released as v2.5.0

**Pull request merged**
