### PR TITLE
add typescript definitions

### PR DESCRIPTION
**Pull request by superbarne**
### Summary

added typescipt definitions for feathers-errors

### CODE REVIEW

**Comment by Alendorff** [comment]
Hi, @daffl, @superbarne.
Right after this change I started to get a TypeScript compilation error. 
```
Compiling...
Using tsc v2.2.1
node_modules/feathers-errors/index.d.ts(68,3): error TS1036: Statements are not allowed in ambient contexts.
node_modules/feathers-errors/index.d.ts(68,3): error TS7028: Unused label.
node_modules/feathers-errors/index.d.ts(70,3): error TS7028: Unused label.

```

**Comment by daffl** [comment]
Fixed in v2.6.1

**Comment by Alendorff** [comment]
Still have it. I just updated library and ensured that I have new version without semicolons but it's still not compile. Errors the same.

**Comment by daffl** [comment]
Can you change the definition in `node_modules/feathers-errors/index.d.ts` and post what would fix it?

**Comment by Alendorff** [comment]
Sorry, but if I knew what was wrong here, I would just send PR :(

**Comment by daffl** [comment]
I don't know what to do here. I really appreciate @superbarne's contributions and everybody else who is helping out on this but I can't help but admit that the whole topic of TypeScript has been a major pain in the virtual behind for the core team (where nobody is using it) ever since it was requested for the first time. 

If it is so difficult to create and maintain definitions for an existing JavaScript project it doesn't speak very well for TypeScript itself and I am starting to reconsider if we are going to support it at all.

**Pull request merged**
