### PR TITLE
move error handler out of index

### PR DESCRIPTION
**Pull request by ekryski**
This is so it doesn't break browser builds and React Native due to the `path` module. This will be a breaking change and the tests need to be updated still.

### CODE REVIEW

**Comment by daffl** [comment]
Let's also not forget to update the generator.

**Comment by ekryski** [comment]
And feathers-memory. We should probably update all the other modules that depend on this but I'm hoping greenkeeper will help us out there.

**Comment by ekryski** [comment]
We'll need to release as a major version and we also need to update the docs. I've got the doc changes local ready to be pushed.

**Comment by daffl** [comment]
We should also add a `middleware.js` file in the root level that re-exports the handler so that you can do `require('feathers-errors/middleware')`.

**Comment by ekryski** [comment]
@daffl you can just do `require('feathers-errors/handler')`. I didn't want to just call it middleware in case we end up adding some other middleware in here for some reason in the future.

**Comment by ekryski** [comment]
Ah I got what you were after. Good catch. This is why we do peer reviews :wink:

**Pull request merged**
